# rebind to CTRL-A
unbind C-b
set -g prefix C-a
bind -r C-a send-prefix
bind C-a last-window

bind a send-key C-a # beginning-of-line
bind e send-key C-e # end-of-line

set -g default-command "${SHELL}"

# message display time
set -g display-time 2000

# start index from 1
set -g base-index 1
set -g pane-base-index 1

# make tmux display things in 256 colors
set -g default-terminal "xterm-256color"
#set -g default-terminal "screen-256color"
# enable 24-bit true color
set -ga terminal-overrides ",xterm*:Tc"

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

# turn off mouse by default
set -g mouse off
# Toggle mouse
bind m set -g mouse on \; display 'Mouse: ON'
bind M set -g mouse off \; display 'Mouse: OFF'

# history limit
set -g history-limit 100000

set -g set-titles on
set -g set-titles-string "#{pane_title}"

# Reload config
unbind r
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#{window_name}"
set -g @catppuccin_window_current_text "#{window_name}"
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

set -g focus-events on

set -g status-position bottom
set -g status-left-length 99
set -g status-right-length 99
set -g status-left ""
set -g status-right ""
#set -ag status-right "#{E:@catppuccin_status_application}"
#set -ag status-right "#{s|$HOME|~|;s|/.*/|/…/|:pane_current_path} "
set -ag status-right "#{E:@catppuccin_status_session}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -g status-justify centre
set -g status-justify left

# load .tmux.conf.local if exists
if-shell "test -r ~/.tmux.conf.local" "source-file ~/.tmux.conf.local"

